export { Home } from './Home';
export { Login } from './Login';
export { Registation } from './Registation';
export { Profile } from './Profile';
export { FullPost } from './FullPost';
export { EditUserData } from './EditUserData';
export { AdminPanel } from './AdminPanel';
export { AddPost } from './AddPost';
export { NotFoundPage } from './404';
